# Generated by Django 4.1 on 2023-04-30 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("assetClass", models.IntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("description", models.CharField(max_length=128)),
                ("position", models.CharField(max_length=128)),
                ("expire", models.IntegerField(default=0)),
                ("count", models.IntegerField(default=1)),
                ("create_time", models.DateField()),
                ("deadline", models.IntegerField()),
                (
                    "initial_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("warning_date", models.IntegerField(default=-1)),
                ("warning_amount", models.IntegerField(default=-1)),
                ("status", models.IntegerField(default=1)),
                ("picture_link", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("userNumber", models.IntegerField(default=0)),
                ("subDepartmentNumber", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("character", models.IntegerField(default=1)),
                ("lock", models.BooleanField(default=False)),
                ("session", models.CharField(default="", max_length=32)),
                ("email", models.EmailField(default="", max_length=32)),
                ("feishu_name", models.CharField(default="", max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="department_staff",
                        to="board.department",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="entity_staff",
                        to="board.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="URL",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=50)),
                ("authority_level", models.IntegerField(default=1)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url",
                        to="board.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingRequests",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.IntegerField()),
                ("result", models.IntegerField(default=0)),
                ("request_time", models.DateTimeField()),
                (
                    "review_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9998,
                            12,
                            31,
                            23,
                            59,
                            59,
                            999999,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_requests",
                        to="board.asset",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_requests",
                        to="board.user",
                    ),
                ),
                (
                    "maintain_asset",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintain_requests",
                        to="board.asset",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_requests",
                        to="board.user",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_requests",
                        to="board.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField()),
                ("operation_type", models.IntegerField()),
                ("object_type", models.IntegerField()),
                ("object_name", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=500)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal",
                        to="board.entity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal",
                        to="board.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department",
                to="board.entity",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="board.department",
            ),
        ),
        migrations.CreateModel(
            name="AssetTree",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("department", models.CharField(max_length=128)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="board.assettree",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asset",
            name="assetTree",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="board.assettree",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="department",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset",
                to="board.department",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="board.asset",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holder",
                to="board.user",
            ),
        ),
    ]
