# Generated by Django 4.1 on 2023-05-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetStatistics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cur_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("cur_time", models.DateTimeField()),
                ("cur_status", models.IntegerField(default=1)),
                ("cur_count", models.IntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_statistics",
                        to="board.asset",
                    ),
                ),
                (
                    "cur_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_statistics",
                        to="board.department",
                    ),
                ),
                (
                    "cur_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_sattistics",
                        to="board.user",
                    ),
                ),
            ],
        ),
    ]
