# Generated by Django 3.2.18 on 2023-05-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_assetstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
    ]
