# Generated by Django 4.1.3 on 2023-05-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_assetstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feishu_open_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
