# Generated by Django 4.1.3 on 2023-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_user_feishu_open_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feishu_user_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
