# Generated by Django 4.1.3 on 2023-05-06 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_user_feishu_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="feishu_user_id",
            new_name="feishu_phone",
        ),
    ]
