# Generated by Django 4.1.3 on 2023-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_rename_feishu_user_id_user_feishu_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingrequests",
            name="feishu_message_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
