# Generated by Django 3.2.18 on 2023-05-07 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_asset_history"),
        ("board", "0006_pendingrequests_feishu_message_id"),
    ]

    operations = []
