# Generated by Django 3.2.18 on 2023-05-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0007_merge_20230507_1913"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="log_journal",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="operation_journal",
            field=models.TextField(blank=True, null=True),
        ),
    ]
