# Generated by Django 3.2.18 on 2023-05-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0008_auto_20230507_1932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="log_journal",
            field=models.TextField(blank=True, default="[]", null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="operation_journal",
            field=models.TextField(blank=True, default="[]", null=True),
        ),
    ]
