# Generated by Django 3.2.18 on 2023-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0009_auto_20230507_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="richtext",
            field=models.CharField(default="", max_length=255),
        ),
    ]
