# Generated by Django 4.1 on 2023-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0010_asset_richtext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="picture_link",
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link_1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link_2",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link_3",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link_4",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link_5",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link_6",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link_7",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link_8",
            field=models.CharField(default="", max_length=255),
        ),
    ]
