# Generated by Django 4.1 on 2023-05-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0011_remove_asset_picture_link_asset_picture_link_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="picture_link_1",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="picture_link_2",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="picture_link_3",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="picture_link_4",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="picture_link_5",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="picture_link_6",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="picture_link_7",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="picture_link_8",
        ),
        migrations.AddField(
            model_name="asset",
            name="picture_link",
            field=models.JSONField(default=list),
        ),
    ]
