# Generated by Django 4.1.3 on 2023-05-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0012_remove_asset_picture_link_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncTasks",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("create_time", models.DateTimeField()),
                ("number_need", models.IntegerField()),
                ("number_succeed", models.IntegerField()),
                ("finish", models.IntegerField()),
                ("failed_message", models.TextField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.entity"
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.user"
                    ),
                ),
            ],
        ),
    ]
