# Generated by Django 4.1.3 on 2023-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0013_asynctasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynctasks",
            name="failed_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asynctasks",
            name="finish",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="asynctasks",
            name="number_need",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="asynctasks",
            name="number_succeed",
            field=models.IntegerField(default=0),
        ),
    ]
