# Generated by Django 4.1 on 2023-05-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0014_alter_asynctasks_failed_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetstatistics",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_statistics",
                to="board.asset",
            ),
        ),
        migrations.AlterField(
            model_name="assetstatistics",
            name="cur_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_sattistics",
                to="board.user",
            ),
        ),
    ]
