# Generated by Django 4.1 on 2023-05-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0015_alter_assetstatistics_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingrequests",
            name="valid",
            field=models.IntegerField(default=1),
        ),
    ]
