# Generated by Django 4.1.3 on 2023-05-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0016_pendingrequests_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="asynctasks",
            name="port_type",
            field=models.IntegerField(default=1),
        ),
    ]
