# Generated by Django 4.1.3 on 2023-05-18 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0017_asynctasks_port_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="richtext",
        ),
    ]
