# Generated by Django 4.1 on 2023-05-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0018_remove_asset_richtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="richtxt",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
