# Generated by Django 4.1 on 2023-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0019_asset_richtxt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="richtxt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assetstatistics",
            name="cur_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=29),
        ),
    ]
